In [35]:
import time
from IPython.display import Image
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
# from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from pandas.plotting import parallel_coordinates
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler # 표준화(평균을 기준)
from sklearn.preprocessing import MinMaxScaler # 정규화(정해진 규칙 기준, mix-max기준)
from sklearn.datasets import load_iris
# cross_val_score: 다양한 샘플링으 ㄹ해서 여러번 테스트 --> 평균치를 구해본다.!
from sklearn.metrics import *
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import LabelEncoder


%matplotlib inline

# 주요 라이브러리 import

from matplotlib import rc, font_manager
import matplotlib.font_manager as fm


# 디렉토리 및 파일 이름에 맞추어 변경
font_location = '../NanumGothic.ttf'
font_name = fm.FontProperties(fname=font_location).get_name()
rc('font', family=font_name)
import scipy.io as spio

from pandas.plotting import parallel_coordinates

In [36]:
df = pd.read_csv('2010summer_dropcol.csv')
df

,Unnamed: 0,sex,age,area,q3,q6,q9,q10,q11,q12,q13,q14,q15,target_q7
0,0,1.0,2.0,2.0,1.0,1.0,6.0,5.0,2.0,6.0,2.0,1.0,1.0,"강이나 계곡, 유원지 등"
1,1,1.0,3.0,4.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,4.0,1.0,해수욕장이나 바다
2,2,1.0,5.0,3.0,1.0,1.0,1.0,1.0,2.0,6.0,2.0,3.0,1.0,해수욕장이나 바다
3,3,2.0,2.0,6.0,1.0,1.0,1.0,4.0,1.0,1.0,2.0,4.0,1.0,"강이나 계곡, 유원지 등"
4,4,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,"강이나 계곡, 유원지 등"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3116,3116,1.0,4.0,6.0,1.0,1.0,1.0,3.0,2.0,4.0,2.0,6.0,5.0,해수욕장이나 바다
3117,3117,2.0,2.0,4.0,1.0,1.0,1.0,4.0,2.0,4.0,2.0,4.0,1.0,"강이나 계곡, 유원지 등"
3118,3118,1.0,3.0,2.0,1.0,1.0,1.0,4.0,2.0,1.0,2.0,6.0,1.0,"강이나 계곡, 유원지 등"
3119,3119,1.0,5.0,5.0,1.0,1.0,1.0,3.0,1.0,5.0,2.0,4.0,1.0,해수욕장이나 바다
3120,3120,2.0,2.0,4.0,1.0,1.0,4.0,2.0,2.0,5.0,2.0,2.0,3.0,해수욕장이나 바다

In [37]:
df.drop(columns='Unnamed: 0', inplace=True)

In [38]:
df

,sex,age,area,q3,q6,q9,q10,q11,q12,q13,q14,q15,target_q7
0,1.0,2.0,2.0,1.0,1.0,6.0,5.0,2.0,6.0,2.0,1.0,1.0,"강이나 계곡, 유원지 등"
1,1.0,3.0,4.0,1.0,1.0,1.0,3.0,2.0,1.0,1.0,4.0,1.0,해수욕장이나 바다
2,1.0,5.0,3.0,1.0,1.0,1.0,1.0,2.0,6.0,2.0,3.0,1.0,해수욕장이나 바다
3,2.0,2.0,6.0,1.0,1.0,1.0,4.0,1.0,1.0,2.0,4.0,1.0,"강이나 계곡, 유원지 등"
4,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,"강이나 계곡, 유원지 등"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3116,1.0,4.0,6.0,1.0,1.0,1.0,3.0,2.0,4.0,2.0,6.0,5.0,해수욕장이나 바다
3117,2.0,2.0,4.0,1.0,1.0,1.0,4.0,2.0,4.0,2.0,4.0,1.0,"강이나 계곡, 유원지 등"
3118,1.0,3.0,2.0,1.0,1.0,1.0,4.0,2.0,1.0,2.0,6.0,1.0,"강이나 계곡, 유원지 등"
3119,1.0,5.0,5.0,1.0,1.0,1.0,3.0,1.0,5.0,2.0,4.0,1.0,해수욕장이나 바다
3120,2.0,2.0,4.0,1.0,1.0,4.0,2.0,2.0,5.0,2.0,2.0,3.0,해수욕장이나 바다

In [39]:
df['target_q7'].value_counts()

해수욕장이나 바다        1240
강이나 계곡, 유원지 등    1054
산이나 국립공원          301
기타                299
문화유적지             145
온천 휴양지             82
Name: target_q7, dtype: int64

In [40]:
df.columns

Index(['sex', 'age', 'area', 'q3', 'q6', 'q9', 'q10', 'q11', 'q12', 'q13',
       'q14', 'q15', 'target_q7'],
      dtype='object')

In [41]:
data = ['sex', 'age', 'area', 'q3', 'q6', 'q9', 'q10', 'q11', 'q12',
       'q13', 'q14', 'q15']
target = 'target_q7'

In [42]:
##data = feature
##target = target

X_train, X_test, y_train, y_test = train_test_split(
    df[data],
    df[target],
    test_size=0.2,
    random_state=42,
    stratify=df[target]
)

## shape 확인
print('----Shape 확인----')
print('X_train:', X_train.shape)
print('y_train:', y_train.shape)
print('X_test:', X_test.shape)
print('y_test', y_test.shape)

## Cross-validation(교차검증)
model_list = []
model_list.append(("LR",LogisticRegression()))
model_list.append(("NB",GaussianNB()))
model_list.append(("RF",RandomForestClassifier()))
model_list.append(("SVC",SVC()))
model_list.append(("Dtree",DecisionTreeClassifier()))
# model_list.append(("XGB",XGBClassifier()))
model_list.append(("KNN",KNeighborsClassifier()))
model_list

def print_cv(model, X_train, y_train, k):
    scores = cross_val_score(model, X_train, y_train, cv = k)
    print(i, k, '----교차검증시작----')
    print('결과:', scores)
    mean_scores = np.mean(scores)
    print('평균:', mean_scores)
    return scores, mean_scores 
# 함수의 결과로 여러개의 데이터를 return
# 튜플로 묶어서 반환하게 된다.(scores, mean_scores)


k_number=[5, 10]
sc_list = []
mean_sc_list = []
for i, model in model_list:
    for k in k_number:
        sc, mean_sc = print_cv(model, X_train, y_train, k)
        sc_list.append(sc)
        mean_sc_list.append(mean_sc)
    print()
print('**********************************************************************************************************************')
print()
print()
print('모델명:', model_list,'k:', k_number)
print()
print()
print('전체 모델의 교차 검증 결과 리스트:')
print(sc_list)
print('전체 모델의 교차 검증 결과 평균:')
print(mean_sc_list)
print()
# 최대 평균값 ==
mean_sc_list_nan = []
for i in mean_sc_list:
    if np.isnan(i):
        pass
    else:
        mean_sc_list_nan.append(i)
max_value = np.max(mean_sc_list_nan)
# 최대 평균값 인덱스 ==


max_index = np.nanargmax(mean_sc_list)
# 최대 평균값 모델명 ==
max_model = model_list[max_index//2][0]
if max_index%2 ==0:
    k_max = 5
else:
    k_max = 10

print('최고 교차 검증 평균>> ', max_value)
print('최고 교차 검증 인덱스>> ', max_index)
print('최고 교차 검증 모델링>> ', max_model, 'k =', k_max)


def grid_search(model, params, k):
    gs_model = GridSearchCV(model, params, cv=k)
    ## gs_model는 최적의 파라메터가 적요된 모델의 객체!
    gs_model.fit(X_train, y_train)
    print('best_estimator:',gs_model.best_estimator_) ##최적의 파라메터가 적용된 모델 객체
    print('best_score:',gs_model.best_score_) ##최적의 파라메터가 적용된 모델로 학습한 정확도 결과(acc)
    print('best_params:',gs_model.best_params_) ##최적의 파라메터
    print('gs_model:',gs_model) #grid_search 객체
    return gs_model.best_estimator_

params = { #하이퍼파라메터 설정으로 가질 수 있는 모든 경우의 수=> 4*3*2: 24
    'max_depth':[3, 5, 7, 10], #key:하이퍼파라메터명, values는 list
    'random_state': [1,3,5],
    'criterion': ['gini','entropy'] #혼란스러운 정도(분류의 정도)를 계산하는 기준
}
best_model = []

for i, model in model_list:
    try:
        print('----clf model:', model, '----')
        best_model.append(grid_search(model, params, 10))
        print()
    except Exception as e:
        print(e)
        print()
print('=====================best_model:', best_model)

## 최적의 하이퍼 파라메터로 모델 객체 생성
## fit()
dt_gs = DecisionTreeClassifier(criterion = 'gini', max_depth=7, random_state=1)
dt_gs.fit(X_train, y_train)
rf_gs = RandomForestClassifier(criterion = 'gini', max_depth=10, random_state=5)
rf_gs.fit(X_train, y_train)

## 테스트 데이터로 검증해보자!
def test_validation(model, X_test, y_test):
    predict_result = model.predict(X_test)
    acc = accuracy_score(y_test, predict_result)
    print("accuracy:", acc)
    cf = confusion_matrix(y_test, predict_result)
    ##실제(c) --> 예측(c, sg), 실제(sg)==> 예측(sg,c),
    # 이진분류(binary classification)인 경우에는
    # 예측할 수 있는 경우의 수는 4가지!
    # 4가지를 표형태로 정리해주는 것이 confusion matrix!
    # 첫반째 행/열은 c, 두번째 행/열은 sg, abc순으로 행/열이 결정
    print('confusion_matrix:\n', cf)
    ## confusion matrix는 binary classfication 인 경우에는 보기가 괜찮으나, 
    ## multi class classification인 경우에는 보기가 힘들어서
    ## classification_report 를 사용하는게 보기 편하다
    c_report = classification_report(y_test, predict_result)
    print('classification_report:\n', c_report)

test_validation(dt_gs, X_test, y_test)

----Shape 확인----
X_train: (2496, 12)
y_train: (2496,)
X_test: (625, 12)
y_test (625,)
LR 5 ----교차검증시작----
결과: [0.442      0.43687375 0.42885772 0.41883768 0.41883768]
평균: 0.4290813627254509
LR 10 ----교차검증시작----
결과: [0.46       0.448      0.432      0.444      0.468      0.4
 0.47389558 0.3815261  0.39759036 0.44176707]
평균: 0.4346779116465863

NB 5 ----교차검증시작----
결과: [0.356      0.33066132 0.42685371 0.32665331 0.32665331]
평균: 0.3533643286573146
NB 10 ----교차검증시작----
결과: [0.348      0.344      0.34       0.328      0.344      0.392
 0.34136546 0.30923695 0.3253012  0.32931727]
평균: 0.3401220883534137

RF 5 ----교차검증시작----
결과: [0.394      0.42885772 0.4008016  0.41482966 0.42885772]
평균: 0.4134693386773547
RF 10 ----교차검증시작----
결과: [0.36       0.392      0.428      0.388      0.452      0.368
 0.41365462 0.42168675 0.41365462 0.41767068]
평균: 0.4054666666666667

SVC 5 ----교차검증시작----
결과: [0.436      0.44488978 0.41883768 0.42084168 0.44288577]
평균: 0.4326909819639278
SVC 10 ----교차검증시작----
결과: [0.468      0.412      0.44       0.444      0.488      0.388
 0.44176707 0.3815261  0.4497992  0.43373494]
평균: 0.43468273092369475

Dtree 5 ----교차검증시작----
결과: [0.278      0.34268537 0.31663327 0.31663327 0.30260521]
평균: 0.31131142284569135
Dtree 10 ----교차검증시작----
결과: [0.296      0.3        0.328      0.308      0.372      0.32
 0.29317269 0.31325301 0.34538153 0.31325301]
평균: 0.3189060240963855

KNN 5 ----교차검증시작----
결과: [0.382      0.3747495  0.36873747 0.35671343 0.38276553]
평균: 0.3729931863727455
KNN 10 ----교차검증시작----
결과: [0.34       0.412      0.352      0.4        0.392      0.352
 0.34538153 0.37349398 0.40963855 0.39759036]
평균: 0.3774104417670683

**********************************************************************************************************************


모델명: [('LR', LogisticRegression()), ('NB', GaussianNB()), ('RF', RandomForestClassifier()), ('SVC', SVC()), ('Dtree', DecisionTreeClassifier()), ('KNN', KNeighborsClassifier())] k: [5, 10]


전체 모델의 교차 검증 결과 리스트:
[array([0.442     , 0.43687375, 0.42885772, 0.41883768, 0.41883768]), array([0.46      , 0.448     , 0.432     , 0.444     , 0.468     ,
       0.4       , 0.47389558, 0.3815261 , 0.39759036, 0.44176707]), array([0.356     , 0.33066132, 0.42685371, 0.32665331, 0.32665331]), array([0.348     , 0.344     , 0.34      , 0.328     , 0.344     ,
       0.392     , 0.34136546, 0.30923695, 0.3253012 , 0.32931727]), array([0.394     , 0.42885772, 0.4008016 , 0.41482966, 0.42885772]), array([0.36      , 0.392     , 0.428     , 0.388     , 0.452     ,
       0.368     , 0.41365462, 0.42168675, 0.41365462, 0.41767068]), array([0.436     , 0.44488978, 0.41883768, 0.42084168, 0.44288577]), array([0.468     , 0.412     , 0.44      , 0.444     , 0.488     ,
       0.388     , 0.44176707, 0.3815261 , 0.4497992 , 0.43373494]), array([0.278     , 0.34268537, 0.31663327, 0.31663327, 0.30260521]), array([0.296     , 0.3       , 0.328     , 0.308     , 0.372     ,
       0.32      , 0.29317269, 0.31325301, 0.34538153, 0.31325301]), array([0.382     , 0.3747495 , 0.36873747, 0.35671343, 0.38276553]), array([0.34      , 0.412     , 0.352     , 0.4       , 0.392     ,
       0.352     , 0.34538153, 0.37349398, 0.40963855, 0.39759036])]
전체 모델의 교차 검증 결과 평균:
[0.4290813627254509, 0.4346779116465863, 0.3533643286573146, 0.3401220883534137, 0.4134693386773547, 0.4054666666666667, 0.4326909819639278, 0.43468273092369475, 0.31131142284569135, 0.3189060240963855, 0.3729931863727455, 0.3774104417670683]

최고 교차 검증 평균>>  0.43468273092369475
최고 교차 검증 인덱스>>  7
최고 교차 검증 모델링>>  SVC k = 10
----clf model: LogisticRegression() ----
Invalid parameter criterion for estimator LogisticRegression(). Check the list of available parameters with `estimator.get_params().keys()`.

----clf model: GaussianNB() ----
Invalid parameter criterion for estimator GaussianNB(). Check the list of available parameters with `estimator.get_params().keys()`.

----clf model: RandomForestClassifier() ----
best_estimator: RandomForestClassifier(max_depth=10, random_state=3)
best_score: 0.448714859437751
best_params: {'criterion': 'gini', 'max_depth': 10, 'random_state': 3}
gs_model: GridSearchCV(cv=10, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 7, 10],
                         'random_state': [1, 3, 5]})

----clf model: SVC() ----
Invalid parameter criterion for estimator SVC(). Check the list of available parameters with `estimator.get_params().keys()`.

----clf model: DecisionTreeClassifier() ----
best_estimator: DecisionTreeClassifier(max_depth=7, random_state=5)
best_score: 0.4126409638554217
best_params: {'criterion': 'gini', 'max_depth': 7, 'random_state': 5}
gs_model: GridSearchCV(cv=10, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 7, 10],
                         'random_state': [1, 3, 5]})

----clf model: KNeighborsClassifier() ----
Invalid parameter criterion for estimator KNeighborsClassifier(). Check the list of available parameters with `estimator.get_params().keys()`.

=====================best_model: [RandomForestClassifier(max_depth=10, random_state=3), DecisionTreeClassifier(max_depth=7, random_state=5)]
accuracy: 0.4144
confusion_matrix:
 [[108   6   0   1   0  96]
 [ 23   8   2   0   0  27]
 [ 14   2   0   0   0  13]
 [ 29   1   0   0   0  30]
 [  4   1   1   0   0  11]
 [ 83  19   2   1   0 143]]
classification_report:
                precision    recall  f1-score   support

강이나 계곡, 유원지 등       0.41      0.51      0.46       211
           기타       0.22      0.13      0.16        60
        문화유적지       0.00      0.00      0.00        29
     산이나 국립공원       0.00      0.00      0.00        60
       온천 휴양지       0.00      0.00      0.00        17
    해수욕장이나 바다       0.45      0.58      0.50       248

     accuracy                           0.41       625
    macro avg       0.18      0.20      0.19       625
 weighted avg       0.34      0.41      0.37       625

In [31]:

dt_gs = DecisionTreeClassifier(criterion = 'gini', max_depth=7, random_state=5)
dt_gs.fit(X_train, y_train)
rf_gs = RandomForestClassifier(criterion = 'entropy', max_depth=10, random_state=1)
rf_gs.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, random_state=1)

In [32]:
test_validation(dt_gs, X_test, y_test)

accuracy: 0.4144
confusion_matrix:
 [[108   5   1   1   0  96]
 [ 23   8   2   0   0  27]
 [ 14   2   0   0   0  13]
 [ 29   1   0   0   0  30]
 [  4   1   1   0   0  11]
 [ 83  19   2   1   0 143]]
classification_report:
                precision    recall  f1-score   support

강이나 계곡, 유원지 등       0.41      0.51      0.46       211
           기타       0.22      0.13      0.17        60
        문화유적지       0.00      0.00      0.00        29
     산이나 국립공원       0.00      0.00      0.00        60
       온천 휴양지       0.00      0.00      0.00        17
    해수욕장이나 바다       0.45      0.58      0.50       248

     accuracy                           0.41       625
    macro avg       0.18      0.20      0.19       625
 weighted avg       0.34      0.41      0.37       625

In [33]:
test_validation(rf_gs, X_test, y_test)

accuracy: 0.4528
confusion_matrix:
 [[106   1   0   1   0 103]
 [ 17   9   1   0   0  33]
 [ 12   0   0   0   0  17]
 [ 25   1   0   1   0  33]
 [  5   1   0   0   0  11]
 [ 74   4   1   2   0 167]]
classification_report:
                precision    recall  f1-score   support

강이나 계곡, 유원지 등       0.44      0.50      0.47       211
           기타       0.56      0.15      0.24        60
        문화유적지       0.00      0.00      0.00        29
     산이나 국립공원       0.25      0.02      0.03        60
       온천 휴양지       0.00      0.00      0.00        17
    해수욕장이나 바다       0.46      0.67      0.55       248

     accuracy                           0.45       625
    macro avg       0.29      0.22      0.21       625
 weighted avg       0.41      0.45      0.40       625